Terminal = {"'!'", "'!='", "'%'", "'%='", "'&&'", "'&'", "'&='", "'('", "')'", "'*'", "'*='",
            "'+'", "'++'", "'+='", "','", "'-'", "'--'", "'-='", "'->'", "'.'", "'...'", "'/'", "'/='",
            "':'", "';'", "'<'", "'<<'", "'<<='", "'<='", "'='", "'=='", "'>'", "'>='", "'>>'", "'>>='", "'?'",
            "'['", "']'", "'^'", "'^='", "'~'", "'{'", "'|'", "'|='", "'||'", "'}'",
            "'auto'", "'break'", "'case'", "'char'", "'const'", "'continue'", "'default'",
            "'do'", "'double'", "'else'", "'enum'", "'extern'", "'float'", "'for'", "'goto'",
            "'if'", "'int'", "'long'", "'register'", "'return'", "'short'", "'signed'",
            "'sizeof'", "'static'", "'struct'", "'switch'", "'typedef'", "'union'",
            "'unsigned'", "'void'", "'volatile'", "'while'",
            'char_const', 'enumeration_const', 'float_const', 'id', 'int_const', 'string'}
